    </div>
    <footer id="footer">
        <div class="footerNav">
            <ul>
                <li><a href="#">Link1</a></li>
                <li><a href="#">Link2</a></li>
                <li><a href="#">Link3</a></li>
                <li><a href="#">Link4</a></li>
            </ul>
            <p>35mm.com 2014</p>
        </div>
    </footer>
</div>

    <script type="text/javascript" src="js/estilos.js"></script>
    <script type="text/javascript" src="js/main.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script type="text/javascript" src="js/jquery.montage.min.js"></script>
    <script src="js/imageGrid.js"></script>
</body>
</html>